from fastapi import FastAPI,Request,HTTPException,status,Depends
#  It creates the "app" object that will listen for requests from the internet.
# request is imported as jinga2 is a requested object.
# from fastapi.responses import HTMLResponse
# for returning html instead of json(raw data) for readability. removed it as we using jinga2.
# HTTPException for proper http responses and status gives status codes that makes it more readable.
# depends is for dependemcy injection to inject a session in routes
from contextlib import asynccontextmanager
from fastapi import Depends, FastAPI, HTTPException, Request, status
from fastapi.exception_handlers import (
    http_exception_handler,
    request_validation_exception_handler,
)

from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles
from fastapi.exceptions import RequestValidationError
# from fastapi.responses import JSONResponse         # not needed as for async we will use default handlers
from starlette.exceptions import HTTPException as StarletteHTTPException
# JSONResponse is used explicitly when you want to send custom metadata or change the HTTP rules of the reply.o return a message and modify the status code manually, or send back custom headers.
# RequestValidationError is just used to send custom error message instead of autogenerated json by the automatic fastapi error handler.
#  Starlette's HTTPException only accepts a status_code and a basic string detail.astAPI's HTTPException allows you to pass custom headers directly inside the exception (which is essential for handling things like security, login tokens, and authentication routing).
from schemas import PostCreate,PostResponse,UserCreate,UserResponse,PostUpdate,UserUpdate
# imported from schemas.py
from typing import Annotated
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload
# select for querying and session for type hintsfor ide

import models
# models give us access to post and user models
from database import Base,engine,get_db
# base and engine for creating tables. get_db the function that provides db 

# Base.metadata.create_all(bind=engine)                  # create all is a sync function and cannot be used with a async engine
# create db tables by looking at models that inherit from base 
@asynccontextmanager
async def lifespan(_app: FastAPI):
    # Startup
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    yield
    # Shutdown
    await engine.dispose()

app= FastAPI(lifespan=lifespan)
# instance of the class(blueprint)for the app that links the code to the web. fastapi is a class here and app is the object created.

app.mount("/static",StaticFiles(directory="static"),name="static")
# mount method takes three arguments . first the url path of static files, second a static file instance pointing to the folder, third a name to reference in templates.
# .mount() is a function that belongs to the FastAPI class. Because app is an object of that class, it has access to this method.
app.mount("/media",StaticFiles(directory="media"),name="media")
templates = Jinja2Templates(directory="templates")
# a template object that knows to look in the templates directory for templates. Jinja2Templates is the class that has the html rendering engine.

# posts: list[dict] = [
#     {
#         "id": 1,
#         "author": "Corey Schafer",
#         "title": "FastAPI is Awesome",
#         "content": "This framework is really easy to use and super fast.",
#         "date_posted": "April 20, 2025",
#     },
#     {
#         "id": 2,
#         "author": "Jane Doe",
#         "title": "Python is Great for Web Development",
#         "content": "Python is a great language for web development, and FastAPI makes it even better.",
#         "date_posted": "April 21, 2025",
#     },
# ] # not needed as we have added a db.

# Route A: Home Page Dashboard view (Aggregated lists)
@app.get("/", include_in_schema=False,name="home")
@app.get("/posts", include_in_schema=False,name="posts")
def home(request: Request, db: Annotated[Session, Depends(get_db)]):
    
    result = db.execute(select(models.Post)) # querying db for all posts for all users
    posts = result.scalars().all()
    
    return templates.TemplateResponse(
        request,
        "home.html", 
        {"posts": posts,"title":"Home"},
        )
# @app wraps the home function with fastapi code. (/)root is the url for when to trigger this function.
# request is added as a paramater for jinga2.
    # Request is a class. FastAPI automatically builds a physical request object packed with data (like their IP address and browser type) and hands it directly to home() function.
# by default fastapi names the routes same as function name and can be changed using name=. when we click homw in the first route it goes to the root of the website.
# we have two dictionary for jinga2 to fetch from posts and title.
    # This calls the Jinja2 engine. It says, "Take an HTML file, fill in the blanks with my Python data, and send the result as a response."
    # request: This is a mandatory requirement for FastAPI templates. It contains all the "behind the scenes" info about the user's connection (their IP, browser type, cookies, etc.). Jinja2 needs this to handle the web communication properly.
    # return {'message': 'Hello World!'}
    # return  f"<h1>{posts[0]['title']}</h1>"

# uv run fastapi dev main.py . dev auto restartes the server when we make changes to code . fastapi run is used in production for performance.
# @app is used to define routes. we created a home route to root url. 
# fastapi api support both sync and async.
# uv is like pip but handles installing Python, managing libraries, and creating environments.
# fastapi converts the dictionary passed into json automatically
# an api endpoint is created returning json in browser
# a swagger ui is generated to show automatic documnetation on http://127.0.0.1:8000/docs. 
# http://127.0.0.1:8000/redoc for more documentation. 
# we add a response class to the decorator and return h1.
# for displaying the same page on two different routes we just stack the decorators
# we dont want to show html routes in documentation as they are meant for users . to make docs clean we use include_in_schema=False in the decorator.
# The .get is the HTTP Method (asking the server for data).
# The "/" is the Path (the home page).
# The @app tells Python this function belongs to your app.

# Route B: Individual Blog Post Detail reader page
@app.get("/posts/{post_id}", include_in_schema=False)
def post_page(request: Request, post_id: int, db: Annotated[Session, Depends(get_db)]):
    # for post in posts:
    #     if post.get("id") == post_id:
    result = db.execute(select(models.Post).where(models.Post.id == post_id))
    post = result.scalars().first() # first grabs the first result
    if post:
            title = post.title[:50] # the title is restricted to upto 50 letters in browser.
            return templates.TemplateResponse(
                request,
                "post.html",
                {"post": post, "title": title},
            )
    raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Post not found")
# By shifting your context dictionary payload parameter from {"posts": posts} to {"post": post}, you stop sending the entire data list to your template layout. You are exclusively passing the specific individual object matching the requested path variable.
# Python loops through your data stack, it pulls out one single dictionary block at a time from the collection and assigns it to the name post.

# Route C: for viewing  a specific users post
@app.get("/users/{user_id}/posts", include_in_schema=False, name="user_posts")
def user_posts_page(
    request: Request,
    user_id: int,
    db: Annotated[Session, Depends(get_db)],
):
    result = db.execute(select(models.User).where(models.User.id == user_id))
    user = result.scalars().first()
    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found",
        )
    result = db.execute(select(models.Post).where(models.Post.user_id == user_id))
    posts = result.scalars().all()
    return templates.TemplateResponse(
        request,
        "user_posts.html",
        {"posts": posts, "user": user, "title": f"{user.username}'s Posts"},
    )

# Route G: Structural Creation endpoint block for processing new user registrations
@app.post(
    "/api/users",
    response_model=UserResponse,
    status_code=status.HTTP_201_CREATED,
) 
def create_user(user: UserCreate,db: Annotated[Session,Depends (get_db)]): # (dependency injection) before running the function get db is called and gives a db session and close when the request is completed.
    result= db.execute(select(models.User).where(models.User.username==user.username), # a select query to check if the user exists. we compare the user.username that we are trying to create to the usernames in db
    )
    existing_user=result.scalars().first() # get the first user object(here object has everthing like id,ussername,etc) if there is one (existing_user becomes a instance of the user class if there is a match) or none if the user doesnt exist

    if existing_user:
         raise HTTPException(
              status_code=status.HTTP_400_BAD_REQUEST,
              detail="Username already exists"
         )
    
    result= db.execute(select(models.User).where(models.User.email==user.email), # checking for existing email
    )
    existing_email=result.scalars().first()  # we dont use existing_user.email() to check as a none earlier will crash everything

    if existing_email:
         raise HTTPException(
              status_code=status.HTTP_400_BAD_REQUEST,
              detail="Email already exists"
         )
    
    new_user=models.User( # creating new user
         username=user.username,
         email=user.email,
         )
    db.add(new_user) 
    db.commit()
    db.refresh(new_user)
# add inserts the user while commit executes it and saves it. refresh reloads the object from db.
    return new_user

# route H : for fetching a specific user. 
@app.get("/api/users/{user_id}", response_model=UserResponse)
def get_users(user_id: int, db: Annotated[Session, Depends(get_db)]):
    result = db.execute(
         select(models.User).where(models.User.id == user_id)) # we compare the user.id table in models to the current user_id to check if the user exists or not.
    user = result.scalars().first()
    if user:
            return user
    # return {"error": "post not found"} # this line is bad as our dev server shows 200(success) instead of a 404(error) as the resource wasnt found at that id.
    raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,detail="user not found")

# route : we fetch all the posts of a specific user
@app.get("/api/users/{user_id}/posts", response_model=list[PostResponse]) # used list as fetching from db the data is not organized and sql alchemy have meta data.
def get_user_posts(user_id: int, db: Annotated[Session, Depends(get_db)]):
    result = db.execute(select(models.User).where(models.User.id == user_id)) # we check if the user exists or not before querying for all posts
    user = result.scalars().first()
    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found",
        )
        
    result = db.execute(select(models.Post).where(models.Post.user_id == user_id))
    posts = result.scalars().all()
    return posts

# route for updating user
@app.patch("/api/users/{user_id}", response_model=UserResponse)
def update_user(
    user_id: int,
    user_update: UserUpdate,                                     # takes the validation from userupdate
    db: Annotated[Session, Depends(get_db)],
):
    result = db.execute(select(models.User).where(models.User.id == user_id)) # checks if the user exists or not
    user = result.scalars().first()
    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found",
        )

    if user_update.username is not None and user_update.username != user.username: # checks if the username is not blank and is differnt from existing one then the username is updated
        result = db.execute(                                                       # blank is not considered as update as it will crash at validation during schema check
            select(models.User).where(models.User.username == user_update.username),
        )
        existing_user = result.scalars().first()
        if existing_user:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Username already exists",
            )

    if user_update.email is not None and user_update.email != user.email:
        result = db.execute(
            select(models.User).where(models.User.email == user_update.email),
        )
        existing_email = result.scalars().first()
        if existing_email:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Email already registered",
            )

    if user_update.username is not None:          # can be done using setattr and dict iteration
        user.username = user_update.username
    if user_update.email is not None:
        user.email = user_update.email
    if user_update.image_file is not None:
        user.image_file = user_update.image_file

    db.commit()
    db.refresh(user)
    return user

# route for deleting a user and all their posts
@app.delete("/api/users/{user_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_user(user_id: int, db: Annotated[Session, Depends(get_db)]):
    result = db.execute(select(models.User).where(models.User.id == user_id))
    user = result.scalars().first()
    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found",
        )

    db.delete(user)
    db.commit()


# Route D: querying all posts and fetching them
@app.get("/api/posts")
def get_posts(db: Annotated[Session, Depends(get_db)]):
    result = db.execute(select(models.Post))
    posts = result.scalars().all()
    return posts
# .get() is an HTTP Method Router.It defines what kind of request server is willing to accept at that specific URL. it is used for reading data.
# returns posts ,another dummy data in json from this route.


# Route F: for creating posts by their user_id 
## Create Post
@app.post(
    "/api/posts",
    response_model=PostResponse,
    status_code=status.HTTP_201_CREATED,
) # a POST request means "Here is some new data, take it and store it." 
# response_model is an optional parameter (or argument) belonging to the @app.post() decorator function.
#  It specifies that when we return new_post, it sends the json data to the PostResponse class for validation.

def create_post(post: PostCreate, db: Annotated[Session, Depends(get_db)]): # Take the incoming JSON data from the internet, run it through the PostCreate bouncer, and convert it into a Python object named post
    # new_id = max(p["id"] for p in posts) + 1 if posts else 1
    # # It looks at your current list of posts, finds the highest "id" number (e.g., 2), adds 1 to it, and says: "Okay, this new post will be ID 3." (If the list is empty, it defaults to 1).
    
    # new_post = {
    #     "id": new_id,
    #     "author": post.author,
    #     "title": post.title,
    #     "content": post.content,
    #     "date_posted": "April 23, 2025",
    # } # post.author fetches only the dictionary key author and assigns its corresponding value to the new dict.
    # # The incoming parameter is defined as post: PostCreate. Because it passes through Pydantic first, post is not a dictionary anymore—it is an Object Instance of the PostCreate class.
    # # Because it’s a Python object instance, we use dot-notation (post.author) to read its attributes, rather than dictionary brackets (post["author"]). Pydantic read the original user JSON key, validated it, and attached it to that object property for you to grab.

    # posts.append(new_post) #It's added to our dictionary list using append temporarily as there is no database yet.
    # return new_post
    result = db.execute(select(models.User).where(models.User.id == post.user_id))
    user = result.scalars().first()
    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found",
        )
    new_post = models.Post(
        title=post.title,
        content=post.content,
        user_id=post.user_id,
    )
    db.add(new_post)
    db.commit()
    db.refresh(new_post)
    return new_post

# Route E: querying for a specific post that matches post_id
@app.get("/api/posts/{post_id}",response_model=PostResponse)
def get_posts(post_id: int, db: Annotated[Session, Depends(get_db)]):
    # for post in posts:
    #     if post.get("id")== post_id:
    result = db.execute(select(models.Post).where(models.Post.id == post_id))
    post = result.scalars().first()
    if post:
            return post
    # return {"error": "post not found"} # this line is bad as our dev server shows 200(success) instead of a 404(error) as the resource wasnt found at that id.
    raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,detail="post not found")
# fastapi automatically provides path validation by displaying a error for wrong type like string when only int is valid.
# return here is not used as python assumes the post_id is invalid but code is flawless hence throws a 200 instead of a 200 on the dev server.
    
# route for full updating a users posts
@app.put("/api/posts/{post_id}", response_model=PostResponse)
def update_post_full(
    post_id: int,
    post_data: PostCreate, # we need the user to fill all fields for the put request and schema check . 
    db: Annotated[Session, Depends(get_db)],
):
    result = db.execute(select(models.Post).where(models.Post.id == post_id))
    post = result.scalars().first()
    if not post:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Post not found"
        )
        
    if post_data.user_id != post.user_id: # right now the app doesnt have a login so user_id can be different for now.
        result = db.execute(              # we check the user_id of the post incoming to the existing post in db . if user_id matches then all good if it doesnt then we assign that user the post after checking that the user actually exists.
            select(models.User).where(models.User.id == post_data.user_id),
        )
        user = result.scalars().first()
        if not user:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="User not found",
            )
    post.title = post_data.title # all fields are replaced in put regarldless same or different.
    post.content = post_data.content
    post.user_id = post_data.user_id
# in the case the post was from a different user_id and not from the owner the post is updated and reassigned to the user while the previous user loses that post.
    db.commit()
    db.refresh(post)
    return post

#route for partially updating a users post
@app.patch("/api/posts/{post_id}", response_model=PostUpdate)
def update_post(
    post_id: int,
    post_data: PostCreate, # we need the user to fill all fields for the put request and schema check . 
    db: Annotated[Session, Depends(get_db)],
):
    result = db.execute(select(models.Post).where(models.Post.id == post_id))
    post = result.scalars().first()
    if not post:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Post not found"
        )
    update_data=post_data.model_dump(exclude_unset=True)   # model_dump a pydantic tool that converts incoming json to a dictionary. exclude_unset=True means that any fields left empty by user are not taken in dict.
    for field,value in update_data.items():
         setattr(post,field,value)                        # does the same thing as assigning the fields that user gave input for. (post,field,value) for that post set the field to the value that the user sent
                                                          # if a user_id doesnt exist that sent the patch req the db will throw error and blocks save.
    db.commit()                                           # if the user_id is differnt and the post registered in a different user_id then the post gets transferrred to that user making put request.
    db.refresh(post)
    return post

# route for deleting a post
@app.delete("/api/posts/{post_id}", status_code=status.HTTP_204_NO_CONTENT) # 204 means success but no response body
def delete_post(post_id: int, db: Annotated[Session, Depends(get_db)]):
    result = db.execute(select(models.Post).where(models.Post.id == post_id))
    post = result.scalars().first()
    if not post:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Post not found"
        )
        
    db.delete(post)
    db.commit()

## StarletteHTTPException Handler
@app.exception_handler(StarletteHTTPException)
def general_http_exception_handler(request: Request, exception: StarletteHTTPException):
    message = (
        exception.detail
        if exception.detail
        else "An error occurred. Please check your request and try again."
        # without ternary operator
        # if exception.detail:
        #     message = exception.detail
        # else:
        #     message = "An error occurred. Please check your request."
        )
# exception.detail it provides the actual text message that goes inside both of those blocks for api and user routes. variable message holds that exception which is then used by our routes.
    if request.url.path.startswith("/api"):
        return JSONResponse(
            status_code=exception.status_code,
            content={"detail": message},
        )
    return templates.TemplateResponse(
        request,
        "error.html",
        {
            "status_code": exception.status_code,
            "title": exception.status_code,
            "message": message,
        },
        status_code=exception.status_code,
    )
# api routes should return json and other routes html page.

### RequestValidationError Handler
@app.exception_handler(RequestValidationError)
def validation_exception_handler(request: Request, exception: RequestValidationError):
    if request.url.path.startswith("/api"):
        return JSONResponse(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            content={"detail": exception.errors()},
        # When backend receives bad data, the RequestValidationError exception doesn't just hold a single error message string. It carries an internal Pydantic method called .errors().
        # When called, .errors() outputs a list of dictionaries that pinpoint exactly where and why the data validation failed.
        )
    
    return templates.TemplateResponse(
        request,
        "error.html",
        {
            "status_code": status.HTTP_422_UNPROCESSABLE_CONTENT,
            "title": status.HTTP_422_UNPROCESSABLE_CONTENT,
            "message": "Invalid request. Please check your input and try again.",
        },
        status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
    )