#  It creates the "app" object that will listen for requests from the internet.
# request is imported as jinga2 is a requested object.
# from fastapi.responses import HTMLResponse
# for returning html instead of json(raw data) for readability. removed it as we using jinga2.
# HTTPException for proper http responses and status gives status codes that makes it more readable.
# depends is for dependemcy injection to inject a session in routes
from contextlib import \
    asynccontextmanager  # handlles the connections and db at startup and shutdown of server by allowing to use a wrapper function in async way
# from schemas import PostCreate,PostResponse,UserCreate,UserResponse,PostUpdate,UserUpdate     # imported from schemas.py . dont need these as we relocated the routes using api router and all schemas are being used in individual routers.
from typing import Annotated

from fastapi import Depends, FastAPI, HTTPException, Request, status
from fastapi.exception_handlers import \
    http_exception_handler  # This is FastAPI's internal built-in manager that handles clean HTTP errors (like custom 404 Post Not Found or 400 Bad Request).
from fastapi.exception_handlers import \
    request_validation_exception_handler  # Global Exception Handlers.; This is the built-in system that automatically catches Pydantic validation errors converts them into those 422 Unprocessable Entity responses.
from fastapi.exceptions import \
    RequestValidationError  # RequestValidationError is just used to send custom error message instead of autogenerated json by the automatic fastapi error handler.
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from sqlalchemy import select  # select for querying
from sqlalchemy.ext.asyncio import \
    AsyncSession  # session for type hints for ide
from sqlalchemy.orm import selectinload
# from fastapi.responses import JSONResponse         # not needed as for async we will be  # JSONResponse is used explicitly when you want to send custom metadata or change the HTTP rules of the reply.o return a message and modify the status code manually, or send back custom headers.
from starlette.exceptions import \
    HTTPException as \
    StarletteHTTPException  # Starlette's HTTPException only accepts a status_code and a basic string detail.astAPI's HTTPException allows you to pass custom headers directly inside the exception (which is essential for handling things like security, login tokens, and authentication routing).

import models  # models give us access to post and user models
from database import (  # base and engine for creating tables. get_db the function that provides db
    Base, engine, get_db)
# Base.metadata.create_all(bind=engine)                  # create all is a sync function and cannot be used with a async engine
# create db tables by looking at models that inherit from base 
from routers import posts, users


@asynccontextmanager                # this blocks tells db tables should be created on startup and cleanup on shutdown of server
async def lifespan(_app: FastAPI):  # _app: FastAPI argument passes the actual app instance into the function.
    # Startup
    async with engine.begin() as conn:   # opens a secure asynchronous connection (conn) to SQLite
        await conn.run_sync(Base.metadata.create_all)  # create_all is a sQLAlchemy’s internal table-creation tool which is sync so we use conn.runsync to prevent blocking our main event loop. await ensures that main event loop pauses until all tables are built
    yield     # here after table creation yield freezes the function in background till the website is active
    # Shutdown                # when uvicorn server is terminated code below yield is executed           
    await engine.dispose()    # this drops all connections,clears ram and closes blog.db cleanly

app= FastAPI(lifespan=lifespan)  # lifespan is passed here which is the manager for opening and closing the async connection. fastapi can now perform according to it around the db engine
# instance of the class(blueprint)for the app that links the code to the web. fastapi is a class here and app is the object created.

app.mount("/static",StaticFiles(directory="static"),name="static")
# mount method takes three arguments . first the url path of static files, second a static file instance pointing to the folder, third a name to reference in templates.
# .mount() is a function that belongs to the FastAPI class. Because app is an object of that class, it has access to this method.
app.mount("/media",StaticFiles(directory="media"),name="media")
templates = Jinja2Templates(directory="templates")              # a template object that knows to look in the templates directory for templates. Jinja2Templates is the class that has the html rendering engine.

app.include_router(users.router, prefix="/api/users", tags=["users"])  # app.includerouter connects the router to our app. the prefix parameter adds that preffix to all the routes in the router. tags creates a section labelled users and group all that endpoints in the docs 
app.include_router(posts.router, prefix="/api/posts", tags=["posts"])  # users.py grabs the specific router = APIRouter() instance defined at the top of that file.

# Route A: fetches all the posts in the db.
@app.get("/", include_in_schema=False,name="home")         # The .get is the HTTP Method (asking the server for data).
@app.get("/posts", include_in_schema=False,name="posts")   # The "/" is the Path (the home page).
async def home(request: Request, db: Annotated[AsyncSession, Depends(get_db)]):  # @app is used to define routes. @app tells Python this function belongs to your app.
    
    result = await db.execute(     # await freezes home function till the sqllite engine fetches the posts in the meanwhile takes other requests in the main event loop. when the query is done it pauses any other req and proceeds with the code in the function.
        select(models.Post)
        .options(selectinload(models.Post.author))   # querying db for all posts for all users and executes a second query to fetch the user detail of the posts(author). sqlalchemy stiches the user data  to the post.author 
        .order_by(models.Post.date_posted.desc()))
    posts = result.scalars().all()
    
    return templates.TemplateResponse(
        request,
        "home.html", 
        {"posts": posts,"title":"Home"},
        )
# @app wraps the home function with fastapi code. (/)root is the url for when to trigger this function.
# request is added as a paramater for jinga2.
    # Request is a class. FastAPI automatically builds a physical request object packed with data (like their IP address and browser type) and hands it directly to home() function.


# Route B: Individual Blog Post Detail reader page
@app.get("/posts/{post_id}", include_in_schema=False)
async def post_page(request: Request, post_id: int, db: Annotated[AsyncSession, Depends(get_db)]):
    # for post in posts:
    #     if post.get("id") == post_id:
    result = await db.execute(
        select(models.Post)
        .options(selectinload(models.Post.author))
        .where(models.Post.id == post_id)
    )
    post = result.scalars().first() # first grabs the first result
    if post:
            title = post.title[:50] # the title is restricted to upto 50 letters in browser.
            return templates.TemplateResponse(
                request,
                "post.html",
                {"post": post, "title": title},
            )
    raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Post not found")
# By shifting your context dictionary payload parameter from {"posts": posts} to {"post": post}, you stop sending the entire data list to your template layout. You are exclusively passing the specific individual object matching the requested path variable.
# Python loops through your data stack, it pulls out one single dictionary block at a time from the collection and assigns it to the name post.

# Route C: for viewing  a specific users post
@app.get("/users/{user_id}/posts", include_in_schema=False, name="user_posts")
async def user_posts_page(
    request: Request,
    user_id: int,
    db: Annotated[AsyncSession, Depends(get_db)],
):
    result = await db.execute(select(models.User).where(models.User.id == user_id))  # selectinload not needed as we are not accessing a relationship
    user = result.scalars().first()
    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found",
        )
    result = await db.execute(
        select(models.Post)
        .options(selectinload(models.Post.author))   # using the relationship to preload the sql alchemy object post,author
        .where(models.Post.user_id == user_id)
        .order_by(models.Post.date_posted.desc()),
    )
    posts = result.scalars().all()
    return templates.TemplateResponse(
        request,
        "user_posts.html",
        {"posts": posts, "user": user, "title": f"{user.username}'s Posts"},
    )

# login and register template_routes.
@app.get("/login", include_in_schema=False) # the server asks to view the login page in this request
async def login_page(request: Request):
    return templates.TemplateResponse(
        request,
        "login.html",
        {"title": "Login"},
    )


@app.get("/register", include_in_schema=False)
async def register_page(request: Request):
    return templates.TemplateResponse(
        request,
        "register.html",
        {"title": "Register"},
    )


# StarletteHTTPException Handler
@app.exception_handler(StarletteHTTPException)
async def general_http_exception_handler(request: Request, exception: StarletteHTTPException):
   
    if request.url.path.startswith("/api"):
        return  await http_exception_handler(request,exception)  # http_exception_handler is a async function and transmitting the http response across a internet socket takes i/o operation we use await so it can process incoming requests for users while the cpu hands over the packets to uvicorn and then to the linux kernel to broadcast.
                                                                 # request for all metadata like url ,ip,socket pipeline of that user the function inspects it . exception has http status like 404(exception.status code) and a message along it like username already exists(exception.detail)
    message = (              # message only needed for templates
        exception.detail     #  exception.detail it provides the actual text message that goes inside both of those blocks for api and user routes. variable message holds that exception which is then used by our routes.
        if exception.detail                                                 # without ternary operator  # if exception.detail:  # message = exception.detail
        else "An error occurred. Please check your request and try again."  # else:  # message = "An error occurred. Please check your request."
    )                                                                       # here exception.detail is only returned if its true like a text message of post not found is there otherwise else
         
    return templates.TemplateResponse(  # this function is sync as all it does it compiling text in ram like jinga replacing the values and packages it to uvicorn which is async that uses an internal await . this code itself isnt streaming anything
        request,
        "error.html",
        {
            "status_code": exception.status_code,
            "title": exception.status_code,
            "message": message,
        },
        status_code=exception.status_code,
    )                                          # api routes should return json and other routes html page.

# RequestValidationError Handler
@app.exception_handler(RequestValidationError)             # When backend receives bad data, the RequestValidationError exception doesn't just hold a single error message string. It carries an internal Pydantic method called .errors().
async def validation_exception_handler(request: Request, exception: RequestValidationError):  # When called, .errors() outputs a list of dictionaries that pinpoint exactly where and why the data validation failed.
    if request.url.path.startswith("/api"):
        return  await request_validation_exception_handler(request,exception)
        
    return templates.TemplateResponse(
        request,
        "error.html",
        {
            "status_code": status.HTTP_422_UNPROCESSABLE_CONTENT,
            "title": status.HTTP_422_UNPROCESSABLE_CONTENT,
            "message": "Invalid request. Please check your input and try again.",
        },
        status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
    )