from fastapi import FastAPI,Request,HTTPException,status,Depends
#  It creates the "app" object that will listen for requests from the internet.
# request is imported as jinga2 is a requested object.
# from fastapi.responses import HTMLResponse
# for returning html instead of json(raw data) for readability. removed it as we using jinga2.
# HTTPException for proper http responses and status gives status codes that makes it more readable.
# depends is for dependemcy injection to inject a session in routes
from contextlib import asynccontextmanager  # handlles the connections and db at startup and shutdown of server by allowing to use a wrapper function in async way
from fastapi import Depends, FastAPI, HTTPException, Request, status
from fastapi.exception_handlers import (  # Global Exception Handlers.
    http_exception_handler,               # This is FastAPI's internal built-in manager that handles clean HTTP errors (like custom 404 Post Not Found or 400 Bad Request).
    request_validation_exception_handler, # This is the built-in system that automatically catches Pydantic validation errors converts them into those 422 Unprocessable Entity responses.
)
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles
from fastapi.exceptions import RequestValidationError  # RequestValidationError is just used to send custom error message instead of autogenerated json by the automatic fastapi error handler.
# from fastapi.responses import JSONResponse         # not needed as for async we will be  # JSONResponse is used explicitly when you want to send custom metadata or change the HTTP rules of the reply.o return a message and modify the status code manually, or send back custom headers.
from starlette.exceptions import HTTPException as StarletteHTTPException #  Starlette's HTTPException only accepts a status_code and a basic string detail.astAPI's HTTPException allows you to pass custom headers directly inside the exception (which is essential for handling things like security, login tokens, and authentication routing).
from schemas import PostCreate,PostResponse,UserCreate,UserResponse,PostUpdate,UserUpdate     # imported from schemas.py
from typing import Annotated
from sqlalchemy import select                    # select for querying 
from sqlalchemy.ext.asyncio import AsyncSession  # session for type hints for ide
from sqlalchemy.orm import selectinload
import models                            # models give us access to post and user models
from database import Base,engine,get_db  # base and engine for creating tables. get_db the function that provides db 
# Base.metadata.create_all(bind=engine)                  # create all is a sync function and cannot be used with a async engine
# create db tables by looking at models that inherit from base 

@asynccontextmanager                # this blocks tells db tables should be created on startup and cleanup on shutdown of server
async def lifespan(_app: FastAPI):  # _app: FastAPI argument passes the actual app instance into the function.
    # Startup
    async with engine.begin() as conn:   # opens a secure asynchronous connection (conn) to SQLite
        await conn.run_sync(Base.metadata.create_all)  # create_all is a sQLAlchemy’s internal table-creation tool which is sync so we use conn.runsync to prevent blocking our main event loop. await ensures that main event loop pauses until all tables are built
    yield     # here after table creation yield freezes the function in background till the website is active
    # Shutdown                # when uvicorn server is terminated code below yield is executed           
    await engine.dispose()    # this drops all connections,clears ram and closes blog.db cleanly

app= FastAPI(lifespan=lifespan)  # lifespan is passed here which is the manager for opening and closing the async connection. fastapi can now perform according to it around the db engine
# instance of the class(blueprint)for the app that links the code to the web. fastapi is a class here and app is the object created.

app.mount("/static",StaticFiles(directory="static"),name="static")
# mount method takes three arguments . first the url path of static files, second a static file instance pointing to the folder, third a name to reference in templates.
# .mount() is a function that belongs to the FastAPI class. Because app is an object of that class, it has access to this method.
app.mount("/media",StaticFiles(directory="media"),name="media")
templates = Jinja2Templates(directory="templates")              # # a template object that knows to look in the templates directory for templates. Jinja2Templates is the class that has the html rendering engine.


# Route A: fetches all the posts in the db.
@app.get("/", include_in_schema=False,name="home")         # The .get is the HTTP Method (asking the server for data).
@app.get("/posts", include_in_schema=False,name="posts")   # The "/" is the Path (the home page).
async def home(request: Request, db: Annotated[AsyncSession, Depends(get_db)]):  # @app is used to define routes. @app tells Python this function belongs to your app.
    
    result = await db.execute(     # await freezes home function till the sqllite engine fetches the posts in the meanwhile takes other requests in the main event loop. when the query is done it pauses any other req and proceeds with the code in the function.
        select(models.Post).options(selectinload(models.Post.author))),   # querying db for all posts for all users and executes a second query to fetch the user detail of the posts(author). sqlalchemy stiches the user data  to the post.author 
    posts = result.scalars().all()
    
    return templates.TemplateResponse(
        request,
        "home.html", 
        {"posts": posts,"title":"Home"},
        )
# @app wraps the home function with fastapi code. (/)root is the url for when to trigger this function.
# request is added as a paramater for jinga2.
    # Request is a class. FastAPI automatically builds a physical request object packed with data (like their IP address and browser type) and hands it directly to home() function.


# Route B: Individual Blog Post Detail reader page
@app.get("/posts/{post_id}", include_in_schema=False)
async def post_page(request: Request, post_id: int, db: Annotated[AsyncSession, Depends(get_db)]):
    # for post in posts:
    #     if post.get("id") == post_id:
    result = await db.execute(
        select(models.Post)
        .options(selectinload(models.Post.author))
        .where(models.Post.id == post_id)
    )
    post = result.scalars().first() # first grabs the first result
    if post:
            title = post.title[:50] # the title is restricted to upto 50 letters in browser.
            return templates.TemplateResponse(
                request,
                "post.html",
                {"post": post, "title": title},
            )
    raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Post not found")
# By shifting your context dictionary payload parameter from {"posts": posts} to {"post": post}, you stop sending the entire data list to your template layout. You are exclusively passing the specific individual object matching the requested path variable.
# Python loops through your data stack, it pulls out one single dictionary block at a time from the collection and assigns it to the name post.

# Route C: for viewing  a specific users post
@app.get("/users/{user_id}/posts", include_in_schema=False, name="user_posts")
async def user_posts_page(
    request: Request,
    user_id: int,
    db: Annotated[AsyncSession, Depends(get_db)],
):
    result = await db.execute(select(models.User).where(models.User.id == user_id))  # selectinload not needed as we are not accessing a relationship
    user = result.scalars().first()
    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found",
        )
    result = await db.execute(
        select(models.Post)
        .options(selectinload(models.Post.author))   # using the relationship to preload the sql alchemy object post,author
        .where(models.Post.user_id == user_id),
    )
    posts = result.scalars().all()
    return templates.TemplateResponse(
        request,
        "user_posts.html",
        {"posts": posts, "user": user, "title": f"{user.username}'s Posts"},
    )

# route for create_user
@app.post(
    "/api/users",
    response_model=UserResponse,
    status_code=status.HTTP_201_CREATED,
)
async def create_user(user: UserCreate, db: Annotated[AsyncSession, Depends(get_db)]):  # (dependency injection) before running the function get db is called and gives a db session and close when the request is completed.
    result = await db.execute(
        select(models.User).where(models.User.username == user.username),  # a select query to check if the user exists. we compare the user.username that we are trying to create to the usernames in db
    )
    existing_user = result.scalars().first()  # get the first user object(here object has everthing like id,ussername,etc) if there is one (existing_user becomes a instance of the user class if there is a match) or none if the user doesnt exist
    if existing_user:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Username already exists",
        )

    result = await db.execute(
        select(models.User).where(models.User.email == user.email),  # checking for existing email
    )
    existing_email = result.scalars().first()  # we dont use existing_user.email() to check as a none earlier will crash everything
    if existing_email:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Email already registered",
        )

    new_user = models.User(  # creating new user
        username=user.username,
        email=user.email,
    )
    db.add(new_user)  # await not used as this just adds the new user to the session memory
    await db.commit()
    await db.refresh(new_user)  # await used here as both operate directly on db
    # add inserts the user while commit executes it and saves it. refresh reloads the object from db because a id and date is assigned which the current object in ram doesnt know.
    return new_user

# route for fetching a specific user. 
@app.get("/api/users/{user_id}", response_model=UserResponse)
async def get_user(user_id: int, db: Annotated[AsyncSession, Depends(get_db)]):
    result = await db.execute(
        select(models.User).where(models.User.id == user_id) # we compare the user.id table in models to the current user_id to check if the user exists or not.
    )
    user = result.scalars().first()
    if user:
        return user
    # return {"error": "post not found"} # this line is bad as our dev server shows 200(success) instead of a 404(error) as the resource wasnt found at that id.
    raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found")

# route : we fetch all the posts of a specific user
@app.get("/api/users/{user_id}/posts", response_model=list[PostResponse]) # used list as fetching from db the data is not organized and sql alchemy have meta data.
async def get_user_posts(user_id: int, db: Annotated[AsyncSession, Depends(get_db)]):
    result = await db.execute(select(models.User).where(models.User.id == user_id)) # we check if the user exists or not before querying for all posts
    user = result.scalars().first()
    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found",
        )
    result = await db.execute(
        select(models.Post)
        .options(selectinload(models.Post.author))
        .where(models.Post.user_id == user_id),
    )
    posts = result.scalars().all()
    return posts

# route for updating users
@app.patch("/api/users/{user_id}", response_model=UserResponse)
async def update_user(
    user_id: int,
    user_update: UserUpdate,                                   # takes the validation from userupdate
    db: Annotated[AsyncSession, Depends(get_db)],
):
    result = await db.execute(select(models.User).where(models.User.id == user_id)) # checks if the user exists or not
    user = result.scalars().first()
    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found",
        )
    if user_update.username is not None and user_update.username != user.username: # checks if the username is not blank and is differnt from existing one then the username is updated
        result = await db.execute(                                                                                 # blank is not considered as update as it will crash at validation during schema check
            select(models.User).where(models.User.username == user_update.username),
        )
        existing_user = result.scalars().first()
        if existing_user:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Username already exists",
            )
    if user_update.email is not None and user_update.email != user.email:
        result = await db.execute(
            select(models.User).where(models.User.email == user_update.email),
        )
        existing_email = result.scalars().first()
        if existing_email:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Email already registered",
            )

    if user_update.username is not None:          # can be done using setattr and dict iteration
        user.username = user_update.username
    if user_update.email is not None:
        user.email = user_update.email
    if user_update.image_file is not None:
        user.image_file = user_update.image_file

    await db.commit()
    await db.refresh(user)
    return user


# route for deleting a user and all their posts
@app.delete("/api/users/{user_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_user(user_id: int, db: Annotated[AsyncSession, Depends(get_db)]):
    result = await db.execute(select(models.User).where(models.User.id == user_id))
    user = result.scalars().first()
    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found",
        )

    await db.delete(user)  # await is used here as the db will have to cascades delete the posts of the user in the relationship.
    await db.commit()


# Route D: querying all posts and fetching them
@app.get("/api/posts", response_model=list[PostResponse])   # .get() is an HTTP Method Router. it is used for reading data.
async def get_posts(db: Annotated[AsyncSession, Depends(get_db)]):
    result = await db.execute(
        select(models.Post).options(selectinload(models.Post.author)),
    )
    posts = result.scalars().all()
    return posts        # returns posts ,(previously) another dummy data in json from this route. now sends data to the response model


# for creating posts by their user_id 
@app.post(                                 # a POST request means "Here is some new data, take it and store it." 
    "/api/posts",  
    response_model=PostResponse,           # Response model specifies that when we return new_post, it sends the json data to the PostResponse class for validation.
    status_code=status.HTTP_201_CREATED,
) 
async def create_post(post: PostCreate, db: Annotated[AsyncSession, Depends(get_db)]): # Take the incoming JSON data from the internet, run it through the PostCreate bouncer, and convert it into a Python object named post
    # new_id = max(p["id"] for p in posts) + 1 if posts else 1     # manual way of assigning ids
     
    # new_post = {"id": new_id, "author": post.author, "title": post.title, "content": post.content, "date_posted": "April 23, 2025",} 
    # post.author fetches only the dictionary key author and assigns its corresponding value to the new dict.
    # The incoming parameter is defined as post: PostCreate. Because it passes through Pydantic first, post is not a dictionary anymore—it is an Object Instance of the PostCreate class.
    # Because it’s a Python object instance, we use dot-notation (post.author) to read its attributes, rather than dictionary brackets (post["author"]). Pydantic read the original user JSON key, validated it, and attached it to that object property for you to grab.
    # posts.append(new_post) #It's added to our dictionary list using append temporarily as there is no database yet.
    # return new_post
    result = await db.execute(
        select(models.User).where(models.User.id == post.user_id),
    )
    user = result.scalars().first()
    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found",
        )

    new_post = models.Post(
        title=post.title,
        content=post.content,
        user_id=post.user_id,
    )
    db.add(new_post)
    await db.commit()
    await db.refresh(new_post, attribute_names=["author"])  # when sqlalchemy fetches the posts table it doesnt fetch a linked column. in our schema for postresponse we need a author field . here attribute_names=["author"] sqlalchemy goes down to the user_id of the post and stiches the data from the users table to the .author
    return new_post

## get_post
# Route for querying for a specific post that matches post_id
@app.get("/api/posts/{post_id}", response_model=PostResponse)
async def get_post(post_id: int, db: Annotated[AsyncSession, Depends(get_db)]):
    result = await db.execute(
        select(models.Post)
        .options(selectinload(models.Post.author))
        .where(models.Post.id == post_id),
    )
    post = result.scalars().first()
    if post:
        return post              # return {"error": "post not found"} # this line is bad as our dev server shows 200(success) instead of a 404(error) as the resource wasnt found at that id.
    raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Post not found")
# fastapi automatically provides path validation by displaying a error for wrong type like string when only int is valid.
# return here is not used as python assumes the post_id is invalid but code is flawless hence throws a 200 instead of a 200 on the dev server.


# route for full updating a users posts
@app.put("/api/posts/{post_id}", response_model=PostResponse)
async def update_post_full(
    post_id: int,
    post_data: PostCreate, # we need the user to fill all fields for the put request and schema check . 
    db: Annotated[AsyncSession, Depends(get_db)],
):
    result = await db.execute(select(models.Post).where(models.Post.id == post_id))
    post = result.scalars().first()
    if not post:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Post not found",
        )
    if post_data.user_id != post.user_id: # right now the app doesnt have a login so user_id can be different for now.
        result = await db.execute(              # we check the user_id of the post incoming to the existing post in db . if user_id matches then all good if it doesnt then we assign that user the post after checking that the user actually exists.
            select(models.User).where(models.User.id == post_data.user_id),
        )
        user = result.scalars().first()
        if not user:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="User not found",
            )

    post.title = post_data.title # all fields are replaced in put regarldless same or different.
    post.content = post_data.content
    post.user_id = post_data.user_id
# in the case the post was from a different user_id and not from the owner the post is updated and reassigned to the user while the previous user loses that post.

    await db.commit()
    await db.refresh(post, attribute_names=["author"])
    return post


#route for partially updating a users post
@app.patch("/api/posts/{post_id}", response_model=PostResponse)
async def update_post_partial(
    post_id: int,
    post_data: PostUpdate, # we need the user to fill all fields for the put request and schema check . 
    db: Annotated[AsyncSession, Depends(get_db)],
):
    result = await db.execute(select(models.Post).where(models.Post.id == post_id))
    post = result.scalars().first()
    if not post:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Post not found",
        )

    update_data = post_data.model_dump(exclude_unset=True)   # model_dump a pydantic tool that converts incoming json to a dictionary. exclude_unset=True means that any fields left empty by user are not taken in dict.
    for field, value in update_data.items():
        setattr(post, field, value)                        # does the same thing as assigning the fields that user gave input for. (post,field,value) for that post set the field to the value that the user sent
                                                          # if a user_id doesnt exist that sent the patch req the db will throw error and blocks save.
    await db.commit()                                           # if the user_id is differnt and the post registered in a different user_id then the post gets transferrred to that user making put request.
    await db.refresh(post, attribute_names=["author"])
    return post


# route for deleting a post
@app.delete("/api/posts/{post_id}", status_code=status.HTTP_204_NO_CONTENT) # 204 means success but no response body
async def delete_post(post_id: int, db: Annotated[AsyncSession, Depends(get_db)]):
    result = await db.execute(select(models.Post).where(models.Post.id == post_id))
    post = result.scalars().first()
    if not post:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Post not found",
        )

    await db.delete(post)
    await db.commit()

# StarletteHTTPException Handler
@app.exception_handler(StarletteHTTPException)
async def general_http_exception_handler(request: Request, exception: StarletteHTTPException):
   
    if request.url.path.startswith("/api"):
        return  await http_exception_handler(request,exception)
    
    message = (              # message only needed for templates
        exception.detail     #  exception.detail it provides the actual text message that goes inside both of those blocks for api and user routes. variable message holds that exception which is then used by our routes.
        if exception.detail                                                 # without ternary operator  # if exception.detail:  # message = exception.detail
        else "An error occurred. Please check your request and try again."  # else:  # message = "An error occurred. Please check your request."
    )
         
    return templates.TemplateResponse(
        request,
        "error.html",
        {
            "status_code": exception.status_code,
            "title": exception.status_code,
            "message": message,
        },
        status_code=exception.status_code,
    )                                          # api routes should return json and other routes html page.

# RequestValidationError Handler
@app.exception_handler(RequestValidationError)             # When backend receives bad data, the RequestValidationError exception doesn't just hold a single error message string. It carries an internal Pydantic method called .errors().
async def validation_exception_handler(request: Request, exception: RequestValidationError):  # When called, .errors() outputs a list of dictionaries that pinpoint exactly where and why the data validation failed.
    if request.url.path.startswith("/api"):
        return  await request_validation_exception_handler(request,exception)
        
    return templates.TemplateResponse(
        request,
        "error.html",
        {
            "status_code": status.HTTP_422_UNPROCESSABLE_CONTENT,
            "title": status.HTTP_422_UNPROCESSABLE_CONTENT,
            "message": "Invalid request. Please check your input and try again.",
        },
        status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
    )